alias npr="npm -s run"
alias lnm="find . -name "node_modules" -type d -prune"
alias nnm="find . -name "node_modules" -type d -prune -exec rm -rf '{}' +"
alias nnmi="nnm && npm i"
alias babel-nodemon="nodemon --exec babel-node -- "
