alias npr="npm -s run"
alias ntr="npm -s run test --"
alias ntw="npm -s run test -- --watch"
alias lnm="find . -name "node_modules" -type d -prune"
alias nnm="find . -name "node_modules" -type d -prune -exec rm -rf '{}' +"
alias nnmi="nnm && npm i"
alias npv="node -p \"require('./package.json').version\""
alias babel-nodemon="nodemon --exec babel-node -- "
alias npmiglobals='npm i -g yarn jscodeshift nodemon bunyan jira-cl git-branch-select git-commits-since cloc'
